//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace registration_app.Services
{
    using System;
    using System.ComponentModel.DataAnnotations;

    public partial class registration
    {
        public int id { get; set; }

        [Required, StringLength(25)]
        [RegularExpression(@"^((?:\+62|62)|08|02)[1-9]{1}[0-9]+$")]
        public string mobile_number { get; set; }

        [Required, StringLength(25)]
        public string first_name { get; set; }

        [Required, StringLength(25)]
        public string last_name { get; set; }

        public Nullable<System.DateTime> date_of_birth { get; set; }

        [StringLength(1)]
        public string gender { get; set; }

        [Required, StringLength(25)]
        [RegularExpression(@"^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$")]
        public string email { get; set; }

    }
}
